config/routes.rb
Rails.application.routes.draw do
  resources :ads  
  root 'ads#index'

end

app/models/ad.rb
class Ad < ActiveRecord::Base
  has_many :creatives
  has_many :targetings
  validates_presence_of :creatives
  validates_presence_of :targetings
  validates :budget, presence: true, numericality: {greater_than: 0}
  accepts_nested_attributes_for :creatives, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :targetings, reject_if: :all_blank, allow_destroy: true
end

app/models/creative.rb
class Creative < ActiveRecord::Base
  attr_accessor :budget

  belongs_to :ad
  validates :bid, presence: true, numericality: {greater_than: 0}
  validates :adtext, presence: true
  validate :bid_less_than_budget

  def bid_less_than_budget
    return if self.bid == nil
    if bid > budget.to_f
      errors.add(:bid, "Bid is greater than budget")
    end
  end
end

app/models/targeting.rb
class Targeting < ActiveRecord::Base
  belongs_to :ad
  enum gender: [ :undefined , :male, :female ]
  #validates :gender, inclusion: {in: %w(:gender)}
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :set_ad, only: [:show, :edit, :update, :destroy]

  # GET /ads
  # GET /ads.json
  def index
    @ads = Ad.paginate :page => params[:page], :per_page => 10
  end

  # GET /ads/1
  # GET /ads/1.json
  def show
  end

  # GET /ads/new
  def new
    @ad = Ad.new
  end

  # GET /ads/1/edit
  def edit
  end

  # POST /ads
  # POST /ads.json
  def create
    @ad = Ad.new(ad_params)

    respond_to do |format|
      if @ad.save
	flash[:success]= 'Ad was successfully created.'
        format.html { redirect_to @ad }
        format.json { render :show, status: :created, location: @ad }
      else
	flash_error
        format.html { render :new }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ads/1
  # PATCH/PUT /ads/1.json
  def update
    respond_to do |format|
      if @ad.update(ad_params)
	flash[:success]= 'Ad was successfully updated.'
        format.html { redirect_to @ad }
        format.json { render :show, status: :ok, location: @ad }
      else
	flash_error
        format.html { render :edit }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ads/1
  # DELETE /ads/1.json
  def destroy
    @ad.destroy
    respond_to do |format|
      flash[:success]="Ad was sucessufully destroyed"
      format.html { redirect_to ads_url }
      format.json { head :no_content }
    end
  end

  private
   def flash_error
      flash[:danger]= @ad.errors.full_messages if not @ad.nil?
   end
    # Use callbacks to share common setup or constraints between actions.
    def set_ad
      @ad = Ad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ad_params
     par = params.require(:ad).permit(:title, :budget, creatives_attributes: [:id, :bid, :adtext, :_destroy], targetings_attributes: [:id,:_destroy, :places, :gender])
     par[:creatives_attributes].each_pair{|key, creative| creative[:budget]=par[:budget]} if par[:creatives_attributes] != nil
     return par
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ads/_creative.html.erb
<ul class="list-group" >
  <li class="list-group-item" >
    <div class="col-sm-2"><strong>Bid: </strong></div>
    &nbsp;<%= number_to_currency creative.bid %>
  </li>
  <li class="list-group-item" >
    <div class="col-sm-2"><strong>Ad text: </strong></div>
    <%= creative.adtext %>
  </li>
</ul>

app/views/ads/_creative_fields.html.erb
<div class="nested-fields"> 
 <%= f.input :bid %>
 <%= f.input :adtext %>
 <%= link_to_remove_association "remove creative", f, :class=>"btn btn-danger" %>
 <hr/>
</div>

app/views/ads/_form.html.erb
<%= simple_form_for(@ad, validate: true,  html: {class: 'form-horizontal' }) do |f| %>
  <%= f.input :title %>
  <%= f.input :budget %>
  <h3>Creatives</h3>
   <div>
    <%= f.simple_fields_for :creatives do |item| %>
      <%= render "creative_fields", f: item %>
    <% end %>
    <%= link_to_add_association 'add creative', f, :creatives, :class=>"btn btn-default" %>
  </div>
  <h3>Targeting</h3>
   <div>
    <%= f.simple_fields_for :targetings do |item| %>
      <%= render "targeting_fields", f: item %>
    <% end %>
    <%= link_to_add_association 'add targeting', f, :targetings, :class=>"btn btn-default" %>
  </div>
  <br/>
  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/ads/_targeting.html.erb
<ul class="list-group" >
  <li class="list-group-item" >
    <div class="col-sm-2"><strong>Places: </strong></div>
    &nbsp;<%= targeting.places %>
  </li>
  <li class="list-group-item" >
    <div class="col-sm-2"><strong>Gender: </strong></div>
    <%= targeting.gender %>
  </li>
</ul>

app/views/ads/_targeting_fields.html.erb
<div class="nested-fields">
    <%= f.input :places %>
    <%= f.input :gender, collection: Targeting.genders.keys, selected: :undefined  %>
 <%= link_to_remove_association "remove targeting", f, :class=>"btn btn-danger" %>
 <hr/>
</div>

app/views/ads/edit.html.erb
<h1>Editing Ad</h1>

<%= render 'form' %>

<br/>
<%= link_to 'Back', ads_path, :class=>"btn btn-default" %>
<%= link_to 'Show', @ad, :class=>"btn btn-default" %> 

app/views/ads/index.html.erb
<h1>Ads</h1>
<div class="text-right">
<%= link_to 'New Ad', new_ad_path, :class=>"btn btn-default" %>
</div>
<table class='table'>
  <thead>
    <tr>
      <th>Ads</th>
      <th class='col-sm-1 col-xs-1' colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ads.each do |ad| %>
      <tr>
        <td><%= ad.title%>
         <%="# #{ad.id}" if ad.title ==nil or ad.title.empty? %>
        </td>
        <td><%= link_to ' ', ad, {:class=> "glyphicon glyphicon-search"} %></td>
        <td><%= link_to ' ', edit_ad_path(ad),{:class=>"glyphicon glyphicon-pencil"} %></td>
        <td><%= link_to ' ', ad, method: :delete, data: { confirm: 'Are you sure?' }, :class=> "glyphicon glyphicon-trash" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="pagination">
  <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

app/views/ads/new.html.erb
<h1>New Ad</h1>

<%= render 'form' %>

<br/>
<%= link_to 'Back', ads_path, :class=>"btn btn-default" %>

app/views/ads/show.html.erb
<h1>Ad</h1>


<ul class="list-group" >
  <li class="list-group-item" >
    <div class="col-sm-2"><strong>Title: </strong></div>
    <%= @ad.title %>&nbsp;
  </li>
  <li class="list-group-item" >
    <div class="col-sm-2"><strong>Budget: </strong></div>
    <%= number_to_currency @ad.budget %>
  </li>
</ul>

<div class="panel panel-info">
  <div class="panel-heading">Creatives</div>
  <div class="panel-body">
    <%= render partial: "creative", collection: @ad.creatives %>
  </div>
</div>

<div class="panel panel-warning">
  <div class="panel-heading">Targetings</div>
  <div class="panel-body">
    <%= render partial: "targeting", collection: @ad.targetings %>
  </div>
</div>

<%= link_to 'Back', ads_path, :class=>"btn btn-default" %>
<%= link_to 'Edit', edit_ad_path(@ad), :class=>"btn btn-default" %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ad-nonsense</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<div class='container size'>
 <% flash.each do |key, value| %>
     <% if value.class == Array %>
       <% value.each do |message| %>
         <p class="alert alert-<%= key %>"><%= message %></p>
       <% end %>
     <% else %>
       <p class="alert alert-<%= key %>"><%= value %></p>
     <% end %>
 <% end %>
 <% flash.clear %>
  <%= yield %>
</div>

</body>
</html>